version: "3"
services:
  ddl-postgres-dev:
    image: postgres:alpine
    container_name: ddl-postgres-dev
    restart: always
    volumes:
      - ~/data/ddl-postgres-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ddl_database
      - POSTGRES_USER=ddl_username
      - POSTGRES_PASSWORD=ddl_password
    ports:
      - '0.0.0.0:5432:5432'
    networks:
      - ddl-dev
  ddl-redis-dev:
    image: redis:alpine
    container_name: ddl-redis-dev
    restart: always
    volumes:
      - ~/data/ddl_redis_dev:/data
    ports:
      - '0.0.0.0:6379:6379'
    networks:
      - ddl-dev
  ddl-rabbitmq-dev:
    image: rabbitmq:management
    container_name: ddl-rabbitmq-dev
    restart: always
    hostname: my-rabbit
    ports:
      - '0.0.0.0:5672:5672'
      - '0.0.0.0:15672:15672'
    volumes:
      - ~/data/ddl_rabbitmq_dev:/var/lib/rabbitmq
    networks:
      - ddl-dev
  ddl-celery-dev:
    command: bash /app/docker/entrypoint-celery-dev.sh
    volumes:
      - .:/app
      - ~/data/upload/problem_test_cases:/upload/problem_test_cases
    build:
      context: .
      dockerfile: Dockerfile
    image: 4ddl/ddlb
    container_name: ddl-celery-dev
    restart: always
    depends_on:
      - ddl-redis-dev
      - ddl-postgres-dev
      - ddl-rabbitmq-dev
    environment:
      - REDIS_HOST=ddl-redis-dev
      - POSTGRES_HOST=ddl-postgres-dev
      - RABBITMQ_HOST=ddl-rabbitmq-dev
    networks:
      - ddl-dev
networks:
  ddl-dev: