version: "3"
services:
  oj-backend-dev:
    command: bash /app/docker/entrypoint-dev.sh
    volumes:
      - .:/app
      - ~/data/backend-data:/data
    image: wustacm/oj-backend
    container_name: oj-backend-dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OJ_ENV=development
      - REDIS_HOST=192.168.50.10
      - POSTGRES_HOST=192.168.50.10
      - RABBITMQ_HOST=192.168.50.10
    ports:
      - "0.0.0.0:8000:8000"