version: "3"
services:
  ddl-backend-dev:
    command: bash /app/docker/entrypoint-dev.sh
    volumes:
      - .:/app
      - ~/data/upload/problem_test_cases:/upload/problem_test_cases
      - ~/data/upload/problem_image:/upload/problem_image
      - ~/data/upload/problem_pdf:/upload/problem_pdf
    image: 4ddl/ddlb
    container_name: ddl-backend-dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=192.168.50.10
      - POSTGRES_HOST=192.168.50.10
      - RABBITMQ_HOST=192.168.50.10
    ports:
      - "0.0.0.0:8000:8000"