# 开发用的databases文件，
version: "3"
services:
  ddl-postgres-dev:
    image: postgres:alpine
    container_name: ddl-postgres-dev
    restart: always
    volumes:
      - ~/data/ddl-postgres-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ddl
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '0.0.0.0:5432:5432'
    networks:
      - ddl-dev
  ddl-redis-dev:
    image: redis:alpine
    container_name: ddl-redis-dev
    restart: always
    volumes:
      - ~/data/ddl-redis-dev:/data
    ports:
      - '0.0.0.0:6379:6379'
    networks:
      - ddl-dev
  ddl-rabbitmq-dev:
    image: rabbitmq:management
    container_name: ddl-rabbitmq-dev
    restart: always
    hostname: my-rabbit
    ports:
      - '0.0.0.0:5672:5672'
      - '0.0.0.0:15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ~/data/ddl-rabbitmq-dev:/var/lib/rabbitmq
    networks:
      - ddl-dev
networks:
  ddl-dev: