# 开发用的databases文件，
version: "3"
services:
  oj-postgres-dev:
    image: postgres:alpine
    container_name: oj-postgres-dev
    restart: always
    volumes:
      - ~/data/oj-postgres-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=oj
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - '0.0.0.0:5432:5432'
  oj-redis-dev:
    image: redis:alpine
    container_name: oj-redis-dev
    restart: always
    volumes:
      - ~/data/oj-redis-dev:/data
    ports:
      - '0.0.0.0:6379:6379'
  oj-rabbitmq-dev:
    image: rabbitmq:management
    container_name: oj-rabbitmq-dev
    restart: always
    hostname: my-rabbit
    ports:
      - '0.0.0.0:5672:5672'
      - '0.0.0.0:15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ~/data/oj-rabbitmq-dev:/var/lib/rabbitmq
