# 本地测试部署的时候运行的所有功能，判题机虚拟使用
version: "3"
services:
  ddl-postgres-dev:
    image: postgres:alpine
    container_name: ddl-postgres
    restart: always
    volumes:
      - ~/data/ddl-postgres-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ddl_database
      - POSTGRES_USER=ddl_username
      - POSTGRES_PASSWORD=ddl_password
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - ddl
  ddl-redis-dev:
    image: redis:alpine
    container_name: ddl-redis
    volumes:
      - ~/data/ddl-redis-dev:/data
    ports:
      - "0.0.0.0:6379:6379"
    networks:
      - ddl
  ddl-rabbitmq-dev:
    image: rabbitmq:management
    container_name: ddl-rabbitmq-dev
    restart: always
    hostname: my-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '0.0.0.0:5672:5672'
      - '0.0.0.0:15672:15672'
    volumes:
      - ~/data/ddl_rabbitmq_dev:/var/lib/rabbitmq
    networks:
      - ddl-dev
  ddl-backend-dev:
    command: bash /app/docker/entrypoint-dev.sh
    volumes:
      - .:/app
      - ~/data/upload/problem_test_cases:/upload/problem_test_cases
      - ~/data/upload/problem_image:/upload/problem_image
      - ~/data/upload/problem_pdf:/upload/problem_pdf
    image: 4ddl/ddlb
    container_name: ddl-backend-dev
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ddl-redis
      - ddl-postgres
    environment:
      - REDIS_HOST=ddl-redis-dev
      - POSTGRES_HOST=ddl-postgres-dev
      - RABBITMQ_HOST=ddl-rabbitmq-dev
    ports:
      - "0.0.0.0:8000:8000"
    networks:
      - ddl
  ddl-web-dev:
    container_name: ddl-web-dev
    image: 4ddl/ddlf
    depends_on:
      - ddl-backend
    environment:
      - BACKEND_HOST=ddl-backend-dev
      - BACKEND_PORT=8000
    ports:
      - "0.0.0.0:80:80"
    networks:
      - ddl
networks:
  ddl:
