FROM ubuntu:20.04

MAINTAINER xudian.cn@gmail.com

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV ddl_env development
RUN mkdir /config
COPY requirements.txt /config
WORKDIR /app
RUN apt-get update
RUN apt-get install python3 python3-dev python3-pip -y
RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install --no-cache-dir -r /config/requirements.txt
