FROM ubuntu:20.04

LABEL maintainer="xudian.cn@gmail.com"
ENV DDL_DEBUG=False
ENV SENTRY_ENABLE=True
ENV TZ=Asia/Shanghai
ENV DDL_ENV=production
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir /config
RUN mkdir /log
COPY requirements.txt /config
COPY docker/supervisord-dev.conf /config
COPY docker/supervisord.conf /config
ADD . /app
WORKDIR /app
RUN apt-get update
RUN apt-get -y install curl zip unzip python3 python3-dev python3-pip supervisor python-is-python3
RUN pip3 install --no-cache-dir -r /config/requirements.txt
RUN pip3 install daphne
