FROM ubuntu:latest

MAINTAINER xudian.cn@gmail.com

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV ddl_env development

ADD . /app
WORKDIR /app
RUN apt-get update
RUN apt-get install git nginx curl unzip supervisor python3 python3-dev python3-pip -y
RUN pip3 install --no-cache-dir -r requirements.txt
CMD bash entrypoint.sh