version: "3"
services:
  ddl-postgres-dev:
    image: postgres:alpine
    container_name: ddl-postgres-dev
    restart: always
    volumes:
      - ~/data/ddl-postgres-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ddl_database
      - POSTGRES_USER=ddl_username
      - POSTGRES_PASSWORD=ddl_password
    ports:
      - '0.0.0.0:5432:5432'
    networks:
      - ddl-dev
  ddl-redis-dev:
    image: redis:alpine
    container_name: ddl-redis-dev
    restart: always
    volumes:
      - ~/data/ddl_redis_dev:/data
    ports:
      - '0.0.0.0:6379:6379'
    networks:
      - ddl-dev
  ddl-celery-dev:
    command: celery -A ddl worker -l info
    volumes:
      - .:/app
      - ~/data/upload/problem_test_cases:/upload/problem_test_cases
    image: registry.cn-hangzhou.aliyuncs.com/dianhsu/ddlb
    container_name: ddl-celery-dev
    restart: always
    depends_on:
      - ddl-redis-dev
      - ddl-postgres-dev
    environment:
      - ddl_env=development
      - REDIS_HOST=ddl-redis-dev
      - POSTGRES_HOST=ddl-postgres-dev
    networks:
      - ddl-dev
  ddl-backend-dev:
    command: bash /app/docker/entrypoint-dev.sh
    volumes:
      - .:/app
      - ~/data/upload/problem_test_cases:/upload/problem_test_cases
      - ~/data/upload/problem_image:/upload/problem_image
      - ~/data/upload/problem_pdf:/upload/problem_pdf
    image: registry.cn-hangzhou.aliyuncs.com/dianhsu/ddlb
    container_name: ddl-backend-dev
    restart: always
    depends_on:
      - ddl-redis-dev
      - ddl-postgres-dev
    environment:
      - ddl_env=development
      - REDIS_HOST=ddl-redis-dev
      - POSTGRES_HOST=ddl-postgres-dev
    ports:
      - '0.0.0.0:8000:8000'
    networks:
      - ddl-dev
networks:
  ddl-dev: