# Generated by Django 3.1.1 on 2020-09-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
