# Generated by Django 3.1.1 on 2020-09-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='last_rejudge_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory_spend',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_spend',
            field=models.IntegerField(null=True),
        ),
    ]
