# Generated by Django 3.1.1 on 2020-09-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.JSONField()),
                ('time_limit', models.IntegerField(default=0)),
                ('memory_limit', models.IntegerField(default=0)),
                ('public', models.IntegerField(choices=[(0, 'Allow view and submit'), (1, 'Allow view'), (2, 'Disabled')], default=0)),
                ('source', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('manifest', models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['id'],
                'permissions': [('view_private_problem', 'Can view private problem'), ('manage_problem', 'Can manage problem')],
            },
        ),
    ]
