# Generated by Django 3.0.8 on 2020-07-31 10:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('time_limit', models.IntegerField(default=0)),
                ('memory_limit', models.IntegerField(default=0)),
                ('public', models.IntegerField(choices=[(0, 'Allow view and submit'), (1, 'Allow view'), (2, 'Disabled')], default=0)),
                ('source', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
