# Generated by Django 3.0.8 on 2020-07-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='userperm',
            name='perm',
            field=models.CharField(choices=[('test', 'test permission')], max_length=6),
        ),
    ]
