# Generated by Django 3.0.8 on 2020-07-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200731_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activated_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
