# Generated by Django 3.0.8 on 2020-07-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200731_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperm',
            name='perm',
            field=models.CharField(choices=[('test', 'test permission, only for test'), ('P_C', 'create problem')], max_length=6),
        ),
    ]
