name: Docker Publish Tags

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Echo Ref
        run: | 
          echo `echo $GITHUB_REF | cut -d '/' -f 3`
      - name: Build Docker image
        run: |
          docker build . --tag ${{ secrets.ALIYUN_IMAGE_DDLB }}:`echo $GITHUB_REF | cut -d '/' -f 3` --file Dockerfile-CI
      - name: Log into Aliyun Container Registry
        run: |
          echo "${{ secrets.ALIYUN_IMAGE_PASS }}" | docker login registry.cn-hangzhou.aliyuncs.com -u ${{ secrets.ALIYUN_IMAGE_USER }} --password-stdin
      - name: Publish Image to Aliyun
        run: |
          docker push ${{ secrets.ALIYUN_IMAGE_DDLB }}:`echo $GITHUB_REF | cut -d '/' -f 3`
