name: Docker Publish Tags

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Echo Ref
        run: | 
          echo `echo $GITHUB_REF | cut -d '/' -f 3`
      - name: Build Docker image
        run: |
          docker build . --tag wustacm/oj-backend:`echo $GITHUB_REF | cut -d '/' -f 3` --file Dockerfile-CI
      - name: Log into Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
      - name: Push Image to Docker Hub
        run: |
          docker push wustacm/oj-backend:`echo $GITHUB_REF | cut -d '/' -f 3`
